name: JJTS Aerial
favicon: null
layout_spectrum: 0.19194
typography_spectrum: 0.20578
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
